apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # common — infrastructure layer
  - argocd-apps/istio.yaml
  - argocd-apps/cert-manager.yaml
  - argocd-apps/istio-crds.yaml
  - argocd-apps/knative.yaml
  - argocd-apps/dex.yaml
  - argocd-apps/oauth2-proxy.yaml
  - argocd-apps/kubeflow-ns.yaml
  - argocd-apps/kubeflow-roles.yaml
  - argocd-apps/kubeflow-istio-resources.yaml
  - argocd-apps/user-namespace.yaml
  - argocd-apps/metacontroller.yaml
  - argocd-apps/istio-namespace.yaml
  # applications — ML platform layer
  - argocd-apps/admission-webhook.yaml
  - argocd-apps/central-dashboard.yaml
  - argocd-apps/jupyter.yaml
  - argocd-apps/notebook-controller.yaml
  - argocd-apps/kserve.yaml
  - argocd-apps/pipeline.yaml
  - argocd-apps/profiles.yaml
  - argocd-apps/pvcviewer-controller.yaml
  - argocd-apps/tensorboard.yaml
  - argocd-apps/trainer.yaml
  - argocd-apps/training-operator.yaml
  - argocd-apps/volumes-web-app.yaml
  - argocd-apps/tensorboards-web-app.yaml   
  - argocd-apps/models-web-app.yaml
