apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/DurojaiyeAbisoye/kubeflow-argocd.git
    targetRevision: main
    path: common/istio/istio-install/overlays/oauth2-proxy
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/preserveUnknownFields
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
      - /webhooks
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
