apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/DurojaiyeAbisoye/kubeflow-argocd.git
    targetRevision: main
    path: common/knative/knative-serving/base
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: webhook.serving.knative.dev
    jsonPointers:
      - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validation.webhook.serving.knative.dev
    jsonPointers:
      - /webhooks
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true