apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profiles
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/DurojaiyeAbisoye/kubeflow-argocd.git
    targetRevision: main
    path: applications/profiles/upstream/overlays/kubeflow
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true