apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: StatefulSet
      namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newTag: v3.3.9
  - name: ghcr.io/dexidp/dex
    newTag: v2.45.1
  - name: public.ecr.aws/docker/library/redis
    newTag: 8.2.3-alpine
  - name: haproxy
    newTag: 3.3.6-alpine