apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/installs/generic/postgres
- ../../base/metadata/overlays/postgres
- ../../third-party/argo/installs/namespace
- ../../third-party/seaweedfs/base
- ../../third-party/postgresql/base
- ../../env/cert-manager/base/cache-cert-issuer.yaml
- ../../env/cert-manager/base/cache-cert.yaml
- ../../env/cert-manager/base/cache-webhook-config.yaml
namespace: kubeflow
labels:
- includeSelectors: true
  pairs:
    application-crd-id: kubeflow-pipelines
